#!/bin/sh

# Remove previous build.
rm wysija-newsletters.zip;

# Create temp dir.
mkdir wysija-newsletters;

# Production assets.
./do compile:all;

# Production libraries.
./composer.phar install --no-dev;

# Copy release folders.
cp -Rf lang wysija-newsletters;
cp -RfL assets wysija-newsletters;
cp -Rf lib wysija-newsletters;
cp -Rf vendor wysija-newsletters;
cp -Rf views wysija-newsletters;
rm -Rf wysija-newsletters/assets/css/src;
rm -Rf wysija-newsletters/assets/js/src;

# Copy release files.
cp LICENSE wysija-newsletters;
cp index.php wysija-newsletters;
cp mailpoet.php wysija-newsletters;
cp readme.txt wysija-newsletters;
cp uninstall.php wysija-newsletters;

# Zip final release.
zip -r wysija-newsletters.zip wysija-newsletters;

# Remove temp dir.
rm -rf wysija-newsletters;

# Reinstall dev dependencies.
./composer.phar install;
