#!/bin/sh

# Remove previous build.
rm wysija-newsletters.zip;

# Create temp dir.
mkdir wysija-newsletters;

# Production assets.
./do compile:all;

# Production libraries.
rm -rf vendor;
rm composer.lock;
./composer.phar install --no-dev;

# Copy release folders.
cp -rf lang wysija-newsletters;
cp -rf assets wysija-newsletters;
cp -rf lib wysija-newsletters;
cp -rf vendor wysija-newsletters;
cp -rf views wysija-newsletters;
rm -rf wysija-newsletters/assets/css/src;
rm -rf wysija-newsletters/assets/js/src;

# Copy release files.
cp LICENSE wysija-newsletters;
cp index.php wysija-newsletters;
cp mailpoet.php wysija-newsletters;
cp readme.txt wysija-newsletters;
cp uninstall.php wysija-newsletters;

# Zip final release.
zip -r wysija-newsletters.zip wysija-newsletters;

# Remove temp dir.
rm -rf wysija-newsletters;

# Reinstall dev dependencies.
rm composer.lock;
./composer.phar install;
./do install;
