export const ACTION_TYPES = {
  START_STANDARD_REQUEST: 'START_STANDARD_REQUEST',
  RECEIVE_STANDARD_NEWSLETTERS: 'RECEIVE_STANDARD_NEWSLETTERS',
  FINISH_STANDARD_REQUEST: 'FINISH_STANDARD_REQUEST',

  START_RE_ENGAGEMENT_REQUEST: 'START_RE_ENGAGEMENT_REQUEST',
  RECEIVE_RE_ENGAMENT: 'RECEIVE_RE_ENGAMENT',
  FINISH_RE_ENGAGEMENT_REQUEST: 'FINISH_RE_ENGAGEMENT_REQUEST', 

  START_POST_NOTIFICATION_REQUEST: 'START_POST_NOTIFICATION_REQUEST',
  RECEIVE_POST_NOTIFICATIONS: 'RECEIVE_POST_NOTIFICATIONS',
  FINISH_POST_NOTIFICATION_REQUEST: 'FINISH_POST_NOTIFICATION_REQUEST',

  RECEIVE_META: 'RECEIVE_META',

  DUPLICATE_NEWSLETTER_REQUEST_START: 'DUPLICATE_NEWSLETTER_REQUEST_START',
  DUPLICATE_NEWSLETTER_REQUEST_SUCCESS: 'DUPLICATE_NEWSLETTER_REQUEST_SUCCESS',
  DUPLICATE_NEWSLETTER_REQUEST_ERROR: 'DUPLICATE_NEWSLETTER_REQUEST_ERROR',
  DUPLICATE_NEWSLETTER_REQUEST_FINISH: 'DUPLICATE_NEWSLETTER_REQUEST_FINISH',
  
  FETCH_NEWSLETTERS_FAILURE: 'FETCH_NEWSLETTERS_FAILURE',
  RECEIVE_ERROR: 'RECEIVE_ERROR',

} as const;
