export const ACTION_TYPES = {
  START_STANDARD_REQUEST: 'START_STANDARD_REQUEST',
  FINISH_STANDARD_REQUEST: 'FINISH_STANDARD_REQUEST',
  RECEIVE_STANDARD_NEWSLETTERS: 'RECEIVE_STANDARD_NEWSLETTERS',
  RECEIVE_STANDARD_SEGMENTS: 'RECEIVE_STANDARD_SEGMENTS',

  START_RE_ENGAGEMENT_REQUEST: 'START_RE_ENGAGEMENT_REQUEST',
  RECEIVE_RE_ENGAMENT: 'RECEIVE_RE_ENGAMENT',
  FINISH_RE_ENGAGEMENT_REQUEST: 'FINISH_RE_ENGAGEMENT_REQUEST', 

  START_POST_NOTIFICATION_REQUEST: 'START_POST_NOTIFICATION_REQUEST',
  RECEIVE_POST_NOTIFICATIONS: 'RECEIVE_POST_NOTIFICATIONS',
  FINISH_POST_NOTIFICATION_REQUEST: 'FINISH_POST_NOTIFICATION_REQUEST',

  FETCH_NEWSLETTERS_FAILURE: 'FETCH_NEWSLETTERS_FAILURE',
  RECEIVE_ERROR: 'RECEIVE_ERROR',

} as const;
