export const ACTION_TYPES = {
  RECEIVE_NEWSLETTERS: 'RECEIVE_NEWSLETTERS',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
  FETCH_NEWSLETTERS_REQUEST: 'FETCH_NEWSLETTERS_REQUEST',
  FETCH_NEWSLETTERS_SUCCESS: 'FETCH_NEWSLETTERS_SUCCESS',
  FETCH_NEWSLETTERS_FAILURE: 'FETCH_NEWSLETTERS_FAILURE',
} as const;
