<?php  //[STAMP] d305d58a783adf00ac0f766f93b4b7f1
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile



trait Actions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
