<?php // phpcs:ignore SlevomatCodingStandard.TypeHints.DeclareStrictTypes.DeclareStrictTypesMissing

namespace MailPoet\Tracy\DIPanel;

/**
 * @var DIPanel $this
 */

?>
<h1>Dependency Injection</h1>
<div class="tracy-inner">
  <h2>Free (<?= count($this->freeServices) ?> services)</h2>
  <table>
    <tr>
      <th>Service</th>
      <th>Used In</th>
    </tr>
    <?php foreach ($this->freeServices as $item): ?>
      <tr>
        <td><?php $this->printItem($item) ?></td>
        <td><?php $this->printUsages($item) ?></td>
      </tr>
    <?php endforeach ?>
  </table>
  <h2>Premium (<?= count($this->premiumServices) ?> services)</h2>
  <table>
    <tr>
      <th>Service</th>
      <th>Used In</th>
    </tr>
    <?php foreach ($this->premiumServices as $item): ?>
      <tr>
        <td><?php $this->printItem($item) ?></td>
        <td><?php $this->printUsages($item) ?></td>
      </tr>
    <?php endforeach ?>
  </table>
</div>
