require 'rake'

namespace :tests do
  require 'rake/testtask'

  Rake::TestTask.new(:all) do |t|
    t.pattern = 'tests/**/*.rb'
  end
end

namespace :test do
  @command = ['foreman run']

  task :all do
    @command.push 'rake tests:all'
    system  @command.join(' ')
  end
end
