name: Email Editor Package Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer vendor dependencies for MailPoet
        id: composer-mailpoet-cache
        uses: actions/cache@v4
        with:
          path: mailpoet/vendor
          key: ${{ runner.os }}-composer-mailpoet-${{ matrix.php-version }}-${{ hashFiles('mailpoet/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-mailpoet-${{ matrix.php-version }}-
            ${{ runner.os }}-composer-mailpoet-

      - name: Cache Composer vendor-prefixed dependencies for MailPoet
        id: vendor-prefixed-cache
        uses: actions/cache@v4
        with:
          path: mailpoet/vendor-prefixed
          key: ${{ runner.os }}-vendor-prefixed-${{ matrix.php-version }}-${{ hashFiles('mailpoet/prefixer/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-prefixer-mailpoet-${{ matrix.php-version }}-
            ${{ runner.os }}-prefixer-mailpoet-

      - name: Cache Composer dependencies for Email Editor
        id: composer-email-editor-cache
        uses: actions/cache@v4
        with:
          path: packages/php/email-editor/vendor
          key: ${{ runner.os }}-composer-email-editor-${{ matrix.php-version }}-${{ hashFiles('packages/php/email-editor/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-email-editor-${{ matrix.php-version }}-
            ${{ runner.os }}-composer-email-editor-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd

      - name: Install tools
        run: |
          COMPOSER_DEV_MODE=1 php tools/install.php
          touch .env
        working-directory: mailpoet

      # Install MailPoet dependencies only if the cache was not hit
      - name: Install mailpoet dependencies
        if: steps.composer-mailpoet-cache.outputs.cache-hit != 'true'
        run: ./tools/vendor/composer.phar install
        working-directory: mailpoet

      # Install Email Editor dependencies only if the cache was not hit
      - name: Install email-editor dependencies
        if: steps.composer-email-editor-cache.outputs.cache-hit != 'true'
        run: ../../../mailpoet/tools/vendor/composer.phar install
        working-directory: packages/php/email-editor

      # Run Email Editor unit tests
      - name: Run email-editor package unit tests
        run: ./vendor/bin/codecept build && ../../../mailpoet/tools/vendor/composer.phar unit-test
        working-directory: packages/php/email-editor

      - name: Run email-editor package integration tests
        run: ../../../mailpoet/tools/vendor/composer.phar integration-test
        working-directory: packages/php/email-editor
