name: Add link to WordPress Playground preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-wp-playground-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check and append description
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          BRANCH_NAME="${{ github.head_ref }}"
          DESCRIPTION="$(gh pr view $PR_NUMBER --json body -q .body)"
          HEADING="## Preview"
          CONTENT="$(printf "${HEADING}\n\n[Preview in WordPress Playground](https://account.mailpoet.com/playground/new/branch:${BRANCH_NAME})\n\n_The latest successful build from \`${BRANCH_NAME}\` will be used. If none is available, the link won't work._")"

          if [[ "$DESCRIPTION" != *"$HEADING"* ]]; then
            gh pr edit $PR_NUMBER --body "$(printf "${DESCRIPTION}\n\n${CONTENT}")"
          fi
